/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import conexao.ModuloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leandro
 */
public class TelaPesquisarInsumos extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    private String cbPesquisar = "codigo";

    /**
     * Creates new form TelaPesquisarInsumos
     */
    public TelaPesquisarInsumos() {
        initComponents();

        this.conexao = ModuloConexao.conector();
        pesquisarInsumos();
    }
     
    public void pesquisarInsumos() {
        String sql = "select * from tbinsumos where " + this.cbPesquisar + " like ?";

        DefaultTableModel modelo = (DefaultTableModel) this.tblCadInsumos.getModel();
        modelo.setNumRows(0);

        this.tblCadInsumos.getColumnModel().getColumn(0).setPreferredWidth(20);
        this.tblCadInsumos.getColumnModel().getColumn(1).setPreferredWidth(80);
        this.tblCadInsumos.getColumnModel().getColumn(2).setPreferredWidth(40);
        this.tblCadInsumos.getColumnModel().getColumn(3).setPreferredWidth(40);
        this.tblCadInsumos.getColumnModel().getColumn(4).setPreferredWidth(40);

        try {
            this.pst = this.conexao.prepareStatement(sql);
            this.pst.setString(1, this.txtPesquisarInsumos.getText() + "%");
            this.rs = this.pst.executeQuery();
            //Preencher a tabela usando a bibliotéca rs2xml.jar
            while (this.rs.next()) {
                modelo.addRow(new Object[]{
                    this.rs.getInt(1),
                    this.rs.getString(2),
                    this.rs.getString(3),
                    this.rs.getString(4),
                    this.rs.getString(5)});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    //seta os campos do formulário com o coteúdo da tabela
    private void setarCampos() {
        int setar = this.tblCadInsumos.getSelectedRow();
        TelaCadInsumo.txtCadInsCodigo.setEnabled(false);
        TelaCadInsumo.txtCadInsCodigo.setText(this.tblCadInsumos.getModel().getValueAt(setar, 0).toString());
        TelaCadInsumo.txtCadInsDes.setText(this.tblCadInsumos.getModel().getValueAt(setar, 1).toString());
        TelaCadInsumo.cbCadInsUm.setSelectedItem(this.tblCadInsumos.getModel().getValueAt(setar, 2).toString());
        TelaCadInsumo.txtCadInsQuant.setText(this.tblCadInsumos.getModel().getValueAt(setar, 3).toString().replace(".", ","));
        TelaCadInsumo.txtCadInsPreco.setText(this.tblCadInsumos.getModel().getValueAt(setar, 4).toString().replace(".", ","));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        cbPesquisarIns = new javax.swing.JComboBox<>();
        txtPesquisarInsumos = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCadInsumos = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pesquisar Insumos");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(858, 560));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Pesquisar por:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 23, -1, -1));

        cbPesquisarIns.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Descrição", "UM", "Quantidade", "Preço" }));
        cbPesquisarIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPesquisarInsActionPerformed(evt);
            }
        });
        getContentPane().add(cbPesquisarIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 48, 153, -1));

        txtPesquisarInsumos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarInsumosKeyReleased(evt);
            }
        });
        getContentPane().add(txtPesquisarInsumos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 74, 216, -1));

        tblCadInsumos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tblCadInsumos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "UM", "Quantidade", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCadInsumos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCadInsumosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCadInsumos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 824, 220));

        setBounds(0, 89, 860, 367);
    }// </editor-fold>//GEN-END:initComponents

    private void tblCadInsumosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCadInsumosMouseClicked
        // seta os campos do formulário através da tabela
        //TelaCadUsuario.
        if (evt.getClickCount() > 1) {
            setarCampos();
            this.dispose();
        }

    }//GEN-LAST:event_tblCadInsumosMouseClicked

    private void txtPesquisarInsumosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarInsumosKeyReleased
        // chama o metodo pesquisar
        pesquisarInsumos();
    }//GEN-LAST:event_txtPesquisarInsumosKeyReleased

    private void cbPesquisarInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPesquisarInsActionPerformed
        // adiciona um valor a variável cbPesquizar
        if (this.cbPesquisarIns.getSelectedItem().equals("Código")) {
            this.cbPesquisar = "codigo";
        } else {
            if (this.cbPesquisarIns.getSelectedItem().equals("Descrição")) {
                this.cbPesquisar = "descricao";
            } else {
                if (this.cbPesquisarIns.getSelectedItem().equals("UM")) {
                    this.cbPesquisar = "UM";
                } else {
                    if (this.cbPesquisarIns.getSelectedItem().equals("Quantidade")) {
                        this.cbPesquisar = "quantidade";
                    } else {
                        this.cbPesquisar = "preco";
                    }
                }
            }
        }
    }//GEN-LAST:event_cbPesquisarInsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbPesquisarIns;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblCadInsumos;
    private javax.swing.JTextField txtPesquisarInsumos;
    // End of variables declaration//GEN-END:variables
}
