/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import conexao.ModuloConexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leandro
 */
public class TelaPesquisarReceita extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    private String cbPesquisar = "codigorec";
    /**
     * Creates new form TelaPesquisarReceita
     */
    public TelaPesquisarReceita() {
        initComponents();
        
        this.conexao = ModuloConexao.conector();
        pesquisarReceita();
    }

    public void pesquisarReceita() {
        String sql = "select * from tbreceita where " + this.cbPesquisar + " like ?";

        DefaultTableModel modelo = (DefaultTableModel) this.tblPesquisarReceita.getModel();
        modelo.setNumRows(0);

        this.tblPesquisarReceita.getColumnModel().getColumn(0).setPreferredWidth(20);
        this.tblPesquisarReceita.getColumnModel().getColumn(1).setPreferredWidth(80);
        this.tblPesquisarReceita.getColumnModel().getColumn(2).setPreferredWidth(40);
        this.tblPesquisarReceita.getColumnModel().getColumn(3).setPreferredWidth(40);
        this.tblPesquisarReceita.getColumnModel().getColumn(4).setPreferredWidth(40);

        try {
            this.pst = this.conexao.prepareStatement(sql);
            this.pst.setString(1, this.txtPesquisarReceita.getText() + "%");
            this.rs = this.pst.executeQuery();
            //Preencher a tabela usando a bibliotéca rs2xml.jar
            while (this.rs.next()) {
                modelo.addRow(new Object[]{
                    this.rs.getInt(1),
                    this.rs.getString(2),
                    this.rs.getString(3),
                    this.rs.getString(4),
                    this.rs.getString(5)});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
     private void setarCampos() {
        int setar = this.tblPesquisarReceita.getSelectedRow();
        TelaCadReceita.txtCadRecCodigo.setEnabled(false);
        TelaCadReceita.txtCadRecCodigo.setText(this.tblPesquisarReceita.getModel().getValueAt(setar, 0).toString());
        TelaCadReceita.txtCadRecDes.setText(this.tblPesquisarReceita.getModel().getValueAt(setar, 1).toString());
        TelaCadReceita.txtCadRecPan.setText(this.tblPesquisarReceita.getModel().getValueAt(setar, 2).toString());
        TelaCadReceita.txtCadRecTipo.setText(this.tblPesquisarReceita.getModel().getValueAt(setar, 3).toString());
        TelaCadReceita.txtCadRecVal.setText(this.tblPesquisarReceita.getModel().getValueAt(setar, 4).toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        txtPesquisarReceita = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPesquisarReceita = new javax.swing.JTable();
        cbPesquisarReceita = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setToolTipText("Pesquisar Receita");
        setMaximumSize(null);

        jLabel6.setText("Pesquisar por:");

        txtPesquisarReceita.setVerifyInputWhenFocusTarget(false);
        txtPesquisarReceita.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarReceitaKeyReleased(evt);
            }
        });

        tblPesquisarReceita.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tblPesquisarReceita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Pantone", "Tipo", "Validade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPesquisarReceita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPesquisarReceitaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPesquisarReceita);

        cbPesquisarReceita.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Descrição", "Pantone", "Tipo", "Validade" }));
        cbPesquisarReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPesquisarReceitaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(cbPesquisarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPesquisarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbPesquisarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(txtPesquisarReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );

        setBounds(0, 0, 860, 367);
    }// </editor-fold>//GEN-END:initComponents

    private void tblPesquisarReceitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPesquisarReceitaMouseClicked
        // seta os campos do formulário através da tabela
        //TelaCadReceita.
        if (evt.getClickCount() > 1) {
            setarCampos();
            this.dispose();
        }
    }//GEN-LAST:event_tblPesquisarReceitaMouseClicked

    private void txtPesquisarReceitaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarReceitaKeyReleased
        // chama o metodo pesquisar
        pesquisarReceita();
    }//GEN-LAST:event_txtPesquisarReceitaKeyReleased

    private void cbPesquisarReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPesquisarReceitaActionPerformed
         // adiciona um valor a variável cbPesquizar
        if (this.cbPesquisarReceita.getSelectedItem().equals("Código")) {
            this.cbPesquisar = "codigorec";
        } else {
            if (this.cbPesquisarReceita.getSelectedItem().equals("Descrição")) {
                this.cbPesquisar = "descricao";
            } else {
                if (this.cbPesquisarReceita.getSelectedItem().equals("Pantone")) {
                    this.cbPesquisar = "pantone";
                } else {
                    if (this.cbPesquisarReceita.getSelectedItem().equals("Tipo")) {
                        this.cbPesquisar = "tipodepasta";
                    } else {
                        this.cbPesquisar = "datavencimento";
                    }
                }
            }
        }
    }//GEN-LAST:event_cbPesquisarReceitaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbPesquisarReceita;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblPesquisarReceita;
    private javax.swing.JTextField txtPesquisarReceita;
    // End of variables declaration//GEN-END:variables
}
