/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import conexao.ModuloConexao;
import dao.InsumoDao;
import dto.InsumoDto;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.NumberFormatter;
import util.SoNumeros;
import util.Util;

/**
 *
 * @author Leandro
 */
public class TelaCadInsumo extends javax.swing.JInternalFrame {

    Connection conexao = null;
    JInternalFrame framePesqInsumo;
    Util frame = new Util();
    TelaPesquisarInsumos insumo = new TelaPesquisarInsumos();

    /**
     * Creates new form TelaCadInsumos
     */
    public TelaCadInsumo() {
        initComponents();
        this.conexao = ModuloConexao.conector();
        this.txtCadInsCodigo.setDocument(new SoNumeros());
        this.txtCadInsPreco.setDocument(new SoNumeros());
        this.txtCadInsQuant.setDocument(new SoNumeros());
        mascaraInsumo();
        limparCampos();
    }

    private void confirmar(boolean confirmar) {
        InsumoDto insumoDto = new InsumoDto();
        InsumoDao insumoDao = new InsumoDao();
        NumberFormat formatter = NumberFormat.getCurrencyInstance();
        formatter.setMaximumFractionDigits(2);

        insumoDto.setCodigo(Integer.parseInt(this.txtCadInsCodigo.getText()));
        insumoDto.setDescricao(this.txtCadInsDes.getText());
        insumoDto.setUm(this.cbCadInsUm.getSelectedItem().toString());
        BigDecimal valorBigDecimal = new BigDecimal(this.txtCadInsQuant.getText().replace(",", ".")).setScale(2);
        insumoDto.setQuantidade(valorBigDecimal);
        insumoDto.setPreco(Double.parseDouble(this.txtCadInsPreco.getText().replace(",", ".")));

        if (confirmar == true) {
            insumoDao.adicionarInsumos(insumoDto);

        } else {
            insumoDao.atualizarInsumos(insumoDto, Integer.parseInt(this.txtCadInsCodigo.getText()));
        }
    }

    private void limparCampos() {
        this.txtCadInsCodigo.setEnabled(true);
        this.txtCadInsCodigo.setText(null);
        this.txtCadInsDes.setText(null);
        this.cbCadInsUm.setSelectedItem("kg");
        this.txtCadInsQuant.setText("0");
        this.txtCadInsPreco.setValue(null);

    }

    //confirma se o codigo já existe
    private boolean confirmaCodigo(String codigo) {
        String sql = "select count (codigo) as total from tbinsumos where codigo ='" + codigo + "';";

        PreparedStatement pst;
        int total = 0;

        try {
            pst = this.conexao.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            total = Integer.parseInt(rs.getString(1));

            pst.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        if (total > 0) {
            return false;
        } else {
            return true;
        }

    }

    // confirma se os campos estão setados
    private boolean verificaCampos() {
        if ((this.txtCadInsCodigo.getText().isEmpty()) || (this.txtCadInsDes.getText().isEmpty()) || (this.txtCadInsPreco.getText().isEmpty()) || (this.txtCadInsQuant.getText().isEmpty())) {
            return false;
        } else {
            return true;
        }
    }

    //mascara para o campo preço/ quantidade(foramato de moeda)
    private void mascaraInsumo() {
        DecimalFormat dFormat2 = new DecimalFormat("#,###.00");
        NumberFormatter formatter2 = new NumberFormatter(dFormat2);

        formatter2.setFormat(dFormat2);
        formatter2.setAllowsInvalid(false);

        this.txtCadInsPreco.setFormatterFactory(new DefaultFormatterFactory(formatter2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadInsAdicionar = new javax.swing.JButton();
        txtCadInsCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCadInsDeletar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbCadInsUm = new javax.swing.JComboBox<>();
        btnCadInsLimpar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtCadInsDes = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCadInsPreco = new javax.swing.JFormattedTextField();
        txtCadInsQuant = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Cadastro de Insumos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCadInsAdicionar.setText("Salvar");
        btnCadInsAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadInsAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadInsAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 79, -1));
        getContentPane().add(txtCadInsCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 140, -1));

        jLabel2.setText("Descrição:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        btnCadInsDeletar.setText("Eliminar");
        btnCadInsDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadInsDeletarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadInsDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 79, -1));

        jLabel3.setText("Unidade de Medida (UM):");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        jLabel4.setText("Quantidade:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jLabel5.setText("Preço:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jLabel1.setText("Código:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        cbCadInsUm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kg", "g", "mg", "L" }));
        getContentPane().add(cbCadInsUm, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 140, -1));

        btnCadInsLimpar.setText("Novo");
        btnCadInsLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadInsLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadInsLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 79, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisar.png"))); // NOI18N
        jButton1.setToolTipText("Pesquisar");
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 30, 30));
        getContentPane().add(txtCadInsDes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 270, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Cadastro de Insumos");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));
        getContentPane().add(txtCadInsPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 270, -1));

        txtCadInsQuant.setEnabled(false);
        getContentPane().add(txtCadInsQuant, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 270, -1));

        setBounds(148, 72, 564, 416);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadInsAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadInsAdicionarActionPerformed
        // chama o metodo adicionar
        boolean total;
        boolean campos;
        // verifica os campos
        campos = verificaCampos();
        if (campos == false) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
        } else {
            //chama o metodo para confirmar se o codigo já existe
            total = confirmaCodigo(this.txtCadInsCodigo.getText());
            if (total == false) {
                confirmar(false);
            } else {
                confirmar(true);
                limparCampos();
            }

        }
    }//GEN-LAST:event_btnCadInsAdicionarActionPerformed

    private void btnCadInsDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadInsDeletarActionPerformed
        // chama o metodo deletar
        if (this.txtCadInsCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Selecione um insumo válido.");
        } else {
            InsumoDao deletar = new InsumoDao();
            deletar.deletarInsumos(Integer.parseInt(this.txtCadInsCodigo.getText()));
            limparCampos();
        }

    }//GEN-LAST:event_btnCadInsDeletarActionPerformed

    private void btnCadInsLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadInsLimparActionPerformed
        // chama o metodo limpar    
        limparCampos();
    }//GEN-LAST:event_btnCadInsLimparActionPerformed
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Chama a TelePesquisarInsumos

        if (this.framePesqInsumo == null) {
            this.framePesqInsumo = new TelaPesquisarInsumos();
        }
        this.insumo.pesquisarInsumos();
        this.frame.comandoInternal(this.framePesqInsumo);
        TelaPesquisarInsumos.confimaTela = true;
        TelaPesquisarInsumos.confirmarEscolha = true;

//        TelaPesquisarInsumos insumos = new TelaPesquisarInsumos();
//        TelaPrincipal.Desktop.add(insumos);
//        insumos.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadInsAdicionar;
    private javax.swing.JButton btnCadInsDeletar;
    private javax.swing.JButton btnCadInsLimpar;
    public static javax.swing.JComboBox<String> cbCadInsUm;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JTextField txtCadInsCodigo;
    public static javax.swing.JTextField txtCadInsDes;
    public static javax.swing.JFormattedTextField txtCadInsPreco;
    public static javax.swing.JTextField txtCadInsQuant;
    // End of variables declaration//GEN-END:variables
}
