/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import conexao.ModuloConexao;
import dto.UsuarioDto;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Leandro
 */
public class TelaPesquisarUsuario extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    private String cbPesquisar = "codigo";
    
    public UsuarioDto guardar = new UsuarioDto();

    /**
     * Creates new form TelaPesquisarUsuario
     */
    public TelaPesquisarUsuario() {
        initComponents();
        this.conexao = ModuloConexao.conector();
        pesquisarUsuario();
    }

    
  
    // pesquizar/ carregar usuarios atraves da tabela
    public void pesquisarUsuario() {
        String sql = "select codigo, nome, login, perfil from tbusuarios where " + this.cbPesquisar + " like ?";

        DefaultTableModel modelo = (DefaultTableModel) this.tblCadUsuario.getModel();
        modelo.setNumRows(0);

        this.tblCadUsuario.getColumnModel().getColumn(0).setPreferredWidth(20);
        this.tblCadUsuario.getColumnModel().getColumn(1).setPreferredWidth(80);
        this.tblCadUsuario.getColumnModel().getColumn(2).setPreferredWidth(40);
        this.tblCadUsuario.getColumnModel().getColumn(3).setPreferredWidth(40);
        

        try {
            this.pst = this.conexao.prepareStatement(sql);
            this.pst.setString(1, this.txtCadUsuarioPesquisar.getText() + "%");
            this.rs = this.pst.executeQuery();
            //Preencher a tabela usando a bibliotéca rs2xml.jar
            while (this.rs.next()) {
                modelo.addRow(new Object[]{
                    this.rs.getInt(1),
                    this.rs.getString(2),
                    this.rs.getString(3),
                    this.rs.getString(4)});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
     private void setarCampos() {
        int setar = this.tblCadUsuario.getSelectedRow();
        TelaCadUsuario.txtCadUsuId.setEnabled(false);
        TelaCadUsuario.txtCadUsuLogin.setEnabled(false);
        TelaCadUsuario.txtCadUsuId.setText(this.tblCadUsuario.getModel().getValueAt(setar, 0).toString());
        TelaCadUsuario.txtCadUsuNome.setText(this.tblCadUsuario.getModel().getValueAt(setar, 1).toString());
        TelaCadUsuario.txtCadUsuLogin.setText(this.tblCadUsuario.getModel().getValueAt(setar, 2).toString());
        TelaCadUsuario.cbCadUsuPerfil.setSelectedItem(this.tblCadUsuario.getModel().getValueAt(setar, 3).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCadUsuario = new javax.swing.JTable();
        txtCadUsuarioPesquisar = new javax.swing.JTextField();
        cbCadUsuarioPesquisar = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Tabela de Usuários");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblCadUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Login", "Perfil"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCadUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCadUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCadUsuario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 390, 250));

        txtCadUsuarioPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCadUsuarioPesquisarKeyReleased(evt);
            }
        });
        getContentPane().add(txtCadUsuarioPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 260, -1));

        cbCadUsuarioPesquisar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nome", "Perfil" }));
        cbCadUsuarioPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCadUsuarioPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(cbCadUsuarioPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, -1));

        jLabel7.setText("Pesquisar por:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        setBounds(209, 77, 441, 406);
    }// </editor-fold>//GEN-END:initComponents

    private void tblCadUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCadUsuarioMouseClicked
        // seta os campos do formulário através da tabela
        //TelaCadUsuario.
        if (evt.getClickCount() > 1) {
            setarCampos();
            this.dispose();
        }
       
    }//GEN-LAST:event_tblCadUsuarioMouseClicked

    private void txtCadUsuarioPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadUsuarioPesquisarKeyReleased
        // chama o metodo pesquisar
        pesquisarUsuario();
    }//GEN-LAST:event_txtCadUsuarioPesquisarKeyReleased

    private void cbCadUsuarioPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCadUsuarioPesquisarActionPerformed
        // adiciona um valor a variável cbPesquizar
        if (this.cbCadUsuarioPesquisar.getSelectedItem().equals("Código")) {
            this.cbPesquisar = "Codigo";
        } else {
            if (this.cbCadUsuarioPesquisar.getSelectedItem().equals("Nome")) {
                this.cbPesquisar = "Nome";
            } else {
                this.cbPesquisar = "Perfil";
            }
        }
    }//GEN-LAST:event_cbCadUsuarioPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbCadUsuarioPesquisar;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblCadUsuario;
    private javax.swing.JTextField txtCadUsuarioPesquisar;
    // End of variables declaration//GEN-END:variables
}
